version: '3.4'

services:
  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    links:
      - "db"
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  db:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "/var/lib/mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: emmy

  nginx:
    build: ./nginx/
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
